### ISSUE TITLE
CoconutKit uses deprecated rotation calls in iOS 8

### ISSUE THREAD

**Issue by danwalkowski** [defagos/CoconutKit#31]
I know that they have just been deprecated in iOS 8, but I am beginning a substantial new project, and am concerned about long-term reliance on CoconutKit.
Do you have plans to update CoconutKit to use - (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator ?

**Comment by defagos** [comment]
Regarding long-term reliance, I will update the code to support the two most recent major iOS versions as long as I work on iOS, since I am using CoconutKit all the time in my projects. I have no intention to stop working on this platform, you should therefore be safe for a few years.

Of course, since CoconutKit is mostly a single-man project, I cannot always work on it as often as I would like. Though I can guarantee that CoconutKit will always be compatible with the two most recent major iOS versions, what I cannot guarantee is when this happens. Depending on the projects I am working on at a given time, I might not always have the time to work on new iOS releases.

Now about rotations. This is a subject which would require a large amount of work if I wanted to support iOS 7 and iOS 8 at the same time. This is something I already made for iOS 5 and 6 rotations a while back, yielding to a lot of wasted code. I haven't the time to do something similar yet, I am sorry.

Since I think rotations won't change anymore with iOS 9, I therefore decided not to rewrite rotation code until the next release, at which point I will completely rethink how rotations are managed in CoconutKit.

I hope this will help you decide what is better for your project.

Regards.

**Comment by danwalkowski** [comment]
Thank you for the info.  I am going to proceed with CoconutKit, since not having to write my own container is a huge time saving.  I appreciate your hard work.

**Comment by defagos** [comment]
Deprecated rotation methods have been removed
